### ISSUE TITLE
column protein2 missing

### ISSUE THREAD

**Issue by maddmagg** [Rappsilber-Laboratory/build-xiview#104]
I constantly have following error:

log id: vl32b11gnhdq0c2i4b8m4k512g_1713274765.log 

With message: Required csv column protein2 missing

<img width="296" alt="XiView error" src="https://github.com/Rappsilber-Laboratory/build-xiview/assets/167211111/4ac1a8d6-1488-4dbd-b96c-ffce24140af9">

Submitted data looks like this:
![image](https://github.com/Rappsilber-Laboratory/build-xiview/assets/167211111/31d7703e-b116-4df9-8d82-54bf85316ae1)

Thanks for help <3

**Comment by colin-combe** [comment]
Hi,
OK, thanks, I will check whats going on.
Could you provide the whole CSV file as submitted, please?

If you prefer not to post it here, you can email it to me at colin.combe@ed.ac.uk,
cheers,
Colin

**Comment by colin-combe** [comment]
i think you might have had quotation marks around the whole lines. 
Its hard to tell from a photo of the open spreadsheet. 
(https://xkcd.com/2116/)
