### ISSUE TITLE
Unable to read mgf files

### ISSUE THREAD

**Issue by bsakc** [Rappsilber-Laboratory/build-xiview#108]
log id:mmacgkfv5e00qtjsp7o96rt4pq_1719841584.log
error type:Error
message:duplicate column(s): matchscore
id: undefined

I have created the mgf files on both proteome discoverer and MSconvert however, i always get this error message and cannot see the spectra matching to the crosslinks. the csv files were produced using xisearch. Please let me know if there is an issue with my workflow

**Comment by bsakc** [comment]
Hi Colin,
thank you for your quick response. I checked the csv file and there is only one column for matchscore. Is there anything else it could be?

Thanks
Adam

**Comment by colin-combe** [comment]
it could be taking spaces out of column names also, so "matchscore" and "Match Score" would count as duplicate column names

**Comment by bsakc** [comment]
Hi Colin

i tried to send you an email yesterday with the csv file but the email could not send for some reason. i have attached it here.
[bsa dss_Xi1.7.6.7.csv](https://github.com/user-attachments/files/16066943/bsa.dss_Xi1.7.6.7.csv)

**Comment by bsakc** [comment]
i have seen your email about the file containing two different matchscores. which one would be best to delete?

**Comment by colin-combe** [comment]
yes... it has "MatchScore" and "match score" and the xiview parser thinks these are the same, which it maybe shouldn't do.
But the easiest thing in short term is just to delete one.
@lutzfischer might have some guidance on which is better to delete?
Or you could make an arbitrary choice just to see if it works.

**Comment by bsakc** [comment]
thank you so much for the help I'll try those now

**Comment by lutzfischer** [comment]
The right one to delete would be `MatchScore`.

**Comment by grandrea** [comment]
I think those columns are part of the xiSEARCH csv output, not of the xiFDR CSM file that is the one that should be uploaded to xiView.

**Comment by colin-combe** [comment]
i think @bsakc has things working now. 

You should upload the mzIdentML file produced by xiFDR.

https://github.com/Rappsilber-Laboratory/XiSearch/issues/107#issuecomment-2213176230
