### ISSUE TITLE
Network not shown - error instead

### ISSUE THREAD

**Issue by cforbrig** [Rappsilber-Laboratory/build-xiview#111]
log id: jnpojuu8om9tccm134kraur7gq_1724765394.log (include this in the github issue)
error type: Error
message: 2
id: undefined

Probably a too large peaklist (33Gb)

![image](https://github.com/user-attachments/assets/9455e599-eced-47f6-95a3-0378f75f68cf)
![image](https://github.com/user-attachments/assets/5e2106d7-8b4a-427a-a101-39187319f574)

**Comment by cforbrig** [comment]
without the zip file with the recalibrated mgf's the network is shown

**Comment by colin-combe** [comment]
yes, the peaklist is probably too large
