### ISSUE TITLE
Translucent overlay sometimes prevents buttons from working if warning or error when uploading a file (public website)

### ISSUE THREAD

**Issue by vrkosk** [Rappsilber-Laboratory/build-xiview#86]
Sometimes when uploading files, there is a warning or an error (e.g. upload mzIdentML and it asks for ion series). When there is a warning or an error, the page shows a popup and gets a translucent overlay:

```
<div class="lean-overlay" style="display: block; position: fixed; z-index: 2147483647; top: 0px; left: 0px; height: 100%; width: 100%; background: rgb(0, 0, 0) none repeat scroll 0% 0%; opacity: 0.5; overflow: auto;"></div>
```

I'm guessing this is meant to show below the popup. In Firefox 91.5.1esr, it's often shown over the popup, so you can't click on any of the buttons. I've seen the same in earlier versions of Firefox too. I can proceed by deleting the div element in DOM Inspector, but I'm sure it's not the intended behaviour. Sometimes the overlay is correctly shown under the popup.

**Comment by colin-combe** [comment]
Hi,
thanks, for bug report.
 
I get this too now - its only just started happening... mysterious. Once this happens its basically broken as you can't interact with anything.

I'll look into it,
Cheers,
Colin

**Comment by colin-combe** [comment]
@vrkosk - hmmm, almost two years later to the day.

I think in more recent versions of FireFox it doesn't happen (I'm using 115.7.0esr). Also, i updated the version of jQuery in case that helps.

Is this still a problem for you?

**Comment by vrkosk** [comment]
I'm not sure how to get the dialog box. I tried uploading a CSV and an mzIdentML file, and neither one prompted for any information to be entered.

**Comment by colin-combe** [comment]
i think it will only show if you upload peaklist data at the same time. Otherwise the info isn't really needed.

**Comment by colin-combe** [comment]
i think that'll be fixed nbow

**Comment by vrkosk** [comment]
Works in both Firefox 115.7.0esr (Windows) and Microsoft Edge 121.0.2277.

**Comment by colin-combe** [comment]
thanks Ville
