### ISSUE TITLE
Missing scrollbars on modification dialog on submit.

### ISSUE THREAD

**Issue by lutzfischer** [Rappsilber-Laboratory/build-xiview#90]
When to many modifications are in the file uploaded the continue button (depending on amount of modifications and probably screen size also some modifications) can dissapear out of the bottom of the dialogue and there is no way to scroll down to the button and press it.

**Comment by colin-combe** [comment]
Yep, will fix. CTRL and - to zoom out browser window might help in short term

**Comment by colin-combe** [comment]
@lutzfischer - think thats fixed
